---
- hosts: all
  become: yes
  tasks:
    - name: I want to install webserver on nodes
      apt:
         name: apache2
         state: present
      when: ansible_os_family == 'Debian'
      
    - name: I want to start webserver on ubuntu nodes
      service:
         name: apache2
         state: started
      when: ansible_os_family == 'Debian'

    - name: I want to install webserver on Redhat nodes
      ansible.buildin.dnf:
         name: httpd
         state: started
      when: ansible_os_family == 'RedHat'

    - name: I want to start webserver on Redhat nodes
      service:
         name: httpd
         state: started
      when: ansible_os_family == 'RedHat'