---
- hosts: all
  become: yes
  tasks:
    - name: I want to install webserver on nodes
      apt:
         name: apache2
         state: present
    - name: I want to start webserver on ubuntu nodes
      service:
         name: apache2
         state: started